### ISSUE TITLE
analyzeStatement cant recognize the table due to backtick placement

### ISSUE THREAD

**Issue by leoch20** [google/zetasql#125]
Hello,

I created a `simpleCatalog` and added `simpleTable`s with names like `some-project.ds.table_name`. 
If I use the `analyzeStatement` with a query with backtick only around the project or project and dataset I get a `Table not found` error.
```sql
select * from `some-project`.ds.table_name 
-- or
select * from `some-project.ds`.table_name 
```

Any tips?

**Comment by pgrivachev** [comment]
As I understand, for the case 
```
select * from `some-project`.ds.table_name
```
the following structure should work:
rootCatalog (`simpleCatalog`) <-- `some-project` (`simpleCatalog`) <-- `ds` (`simpleCatalog`) <-- `table_name` (`simpleTable`)
and for 
```
select * from `some-project.ds`.table_name
```
try to use:
rootCatalog (`simpleCatalog`) <-- `some-project.ds` (`simpleCatalog`) <-- `table_name` (`simpleTable`)

**Comment by leoch20** [comment]
Thanks! That got it going
