### ISSUE TITLE
com.google.zetasql.SqlException: Syntax error: Unexpected "-" [at 1:34]

### ISSUE THREAD

**Issue by yonuskula** [google/zetasql#19]
Hi, I have started to use Dataflow SQL. When I run following query   ı have trouble  with date  whose format is YYYY-MM-DD. 

Executing SQL query: 
select * from bigquery.table.coca-cola-data-lake.SPARC.sparc_output_daily where transfer_date = "2019-11-10"

**Comment by jshute111** [comment]
The error is coming from the table name, not the date literal.  You
currently need to quote table names that include dashes with backticks, like
FROM  bigquery.table.`coca-cola-data-lake`.SPARC.sparc_output_daily

**Comment by yonuskula** [comment]
Yeah, you are right.
