### ISSUE TITLE
Function equal not found in a join statement

### ISSUE THREAD

**Issue by karim-fc** [google/zetasql#35]
Analyzer.analyzeStatement gives the following error when giving a sql statement with an inner join:
```
com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Function not found: `$equal` [at 1:153]
```

The sql statement: 
```
SELECT tb.* FROM `project-id`.test_dataset.test_view as vw INNER JOIN `project-id`.test_dataset.test_table as tb ON tb.colA = vw.colA;
```

I also add all the language features this way:
```
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
AnalyzerOptions options = new AnalyzerOptions();
options.setLanguageOptions(languageOptions);

ResolvedStatement rs = Analyzer.analyzeStatement(sql, options, catalog);
```
The code works without a join.

What do I do wrong?

**Comment by amaliujia** [comment]
I think you need to set into `languageOptions.enableMaximumLanguageFeatures()` `ZetaSQLBuiltinFunctionOptionsProto`

**Comment by karim-fc** [comment]
Thank you very much, works like a charm.

You can do:
```
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions());
```
because the default constructor will enable max language features by default.

**Comment by amaliujia** [comment]
Thanks for letting me know that default constructor enable max language features already!
