### ISSUE TITLE
FORMAT() is not a recognized function

### ISSUE THREAD

**Issue by kirajen** [google/zetasql#40]
I get an error whenever I try to parse a query which makes use of the FORMAT function. Ive added all available functions to the catalog (even though i cannot see one for formatting).  Has anyone else had and solved this issue?

**Comment by matthewcbrown** [comment]
This is a known issue (I'm working on it right now actually).  ETA end of month.

**Comment by kirajen** [comment]
sounds good, thanks!

**Comment by kirajen** [comment]
@matthewcbrown is there any news on this?

**Comment by matthewcbrown** [comment]
Ah, done as of last week :)
