### ISSUE TITLE
Dealing with scripting in big query sql

### ISSUE THREAD

**Issue by 244079916** [google/zetasql#44]
Assume I have something like following in .sql file:

DECLARE var1 STRING;
DECLARE var2 INT64;
SET var1 = (
                            SELECT GUID  
                            FROM `project.dataset.table1` 
                            WHERE some_conditions
                            LIMIT 1
                            );
SET var2 = (
                            SELECT A.B   
                            FROM `project.dataset.table2` 
                            WHERE some_conditions
                            LIMIT 1
                            );

INSERT `project.dataset.table3`  
VALUES (value1, value2, value3);

Based on my knowledge that ZetaSQL is not supporting scripting, so I am wondering what's the best way to deal with scripting while parsing the .sql files with ZetaSQL Java implementation.

Thanks,

**Comment by matthewcbrown** [comment]
C++ API is still unstable for the most part (we don't recommend attempting to use it), except ExtractTableNamesFromScript.  I'll add java support for that method, but general support for scripting in java is not on the roadmap.

**Comment by 244079916** [comment]
@matthewcbrown 

Thanks for your reply, I am wondering if there is a timeline? And how to differentiate scripting and sql?

**Comment by matthewcbrown** [comment]
Timeline is, hopefully, later today, or Monday at the latest. 
Anything with a semi colon (;) (outside of comments and strings obviously) is almost certainly a script.
However, any valid SQL is also a valid script, so if you are only using the (soon to be added) extractTableNamesFromScript method, it should work for everything.
If you are doing more complex stuff (like dealing with the ResolvedAST), this only works on SQL. We're talking about how we could add an API to do static analysis of scripts, but it gets a little tricky with DDL, branching and looping. So, no timeline on when we could have that.

**Comment by 244079916** [comment]
Thank you so much for the reply.

Looking forward to the extractTableNamesFromScript.

**Comment by matthewcbrown** [comment]
github is updated, but maven release will be delayed likely until 2020-09-01

**Comment by matthewcbrown** [comment]
should be available in maven central now, version 2020.09.1
