### ISSUE TITLE
Implicit aliases in FROM statement not working

### ISSUE THREAD

**Issue by cthrysoe** [google/zetasql#49]
Hello, I have the following query form
```
select column
  from `projcet1.dataset1.tablename1`
  left join dataset2.tablename2
  on column = tablename2.column
  ...
```
From the documentation (https://github.com/google/zetasql/blob/master/docs/query-syntax.md#implicit-aliases): "For path expressions, the alias is the last identifier in the path. For example, FROM abc.def.ghi implies AS ghi", therefore, I would expect an alias to be created with the name `tablename2`

However, when I run:
```
ResolvedNodes.ResolvedStatement statement = analyzer.analyzeStatement(sql);
```
I get the error, `com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: tablename2` - The same query executes successfully in BigQuery.
I have the following language options enabled:
```
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions());
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
AnalyzerOptions options = new AnalyzerOptions();
options.setPruneUnusedColumns(true);
options.setLanguageOptions(languageOptions);
return new Analyzer(options, catalog)
```

Someone know if I have to enable some additional language settings, or how to achieve the expected behavior?
Thanks!

**Comment by jshute111** [comment]
This should work.  Can you reduce it to a minimal query that reproduces the
error, and show the whole query and the exact error message with location?

**Comment by cthrysoe** [comment]
Hi @jshute111 thank you for your reply.

Here is a small example:
```
String sql1 = "SELECT column1 from `project1.dataset1.table1` test1 left join `dataset2.table2` on test1.column1 = table2.column2";
SimpleCatalog catalog = new SimpleCatalog("tableCatalog");
SimpleColumn column1 = new SimpleColumn("project1.dataset1.table1", "column1",TypeFactory.createSimpleType(ZetaSQLType.TypeKind.TYPE_STRING));
SimpleColumn column2 = new SimpleColumn("dataset2.table2", "column2", TypeFactory.createSimpleType(ZetaSQLType.TypeKind.TYPE_STRING));
SimpleTable simpleTable1 = new SimpleTable("project1.dataset1.table1", Collections.singletonList(column1));
SimpleTable simpleTable2 = new SimpleTable("dataset2.table2", Collections.singletonList(column2));
catalog.addSimpleTable(simpleTable1);
catalog.addSimpleTable(simpleTable2);
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions());
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
AnalyzerOptions options = new AnalyzerOptions();
options.setLanguageOptions(languageOptions);
Analyzer analyzer = new Analyzer(options, catalog);
analyzer.analyzeStatement(sql1);
```
I get the error:

```
Exception in thread "main" com.google.zetasql.SqlException: Unrecognized name: table2 [at 1:101]
	at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:62)
	at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:48)
	at dependencyparser.Main.main(Main.java:54)
Caused by: com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: table2 [at 1:101]
	at com.google.zetasql.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at com.google.zetasql.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at com.google.zetasql.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.google.zetasql.ZetaSqlLocalServiceGrpc$ZetaSqlLocalServiceBlockingStub.analyze(ZetaSqlLocalServiceGrpc.java:1063)
	at com.google.zetasql.Analyzer.analyzeStatement(Analyzer.java:60)
	... 2 more

Caused by: com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: table2 [at 1:101]
```

**Note:** One thing I am seeing is that whenever I don't put backticks around the table names in the query I get a `Table not found error`, for example when using this query instead:
```
SELECT column1 from project1.dataset1.table1 test1 left join `dataset2.table2` on test1.column1 = table2.column2
```
I get the error `com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Table not found: project1.dataset1.table1 [at 1:21]`  
Maybe the issue is that I am adding the tables/columns in a wrong way. Does the above look wrong to you.
Thank you.

**Comment by jshute111** [comment]
The implicit alias is the last identifier in the path.  When you have
something backtick-quoted, that is one identifier.  So if you have
xxx.`a.b`, the alias added will be `a.b`, not `b`.

The way you construct your Catalog, it looks like you are giving tables a
name with one identifier with dots in it, which requires quoting.  If you
want paths to work with multiple identifiers, you can set those up with
sub-catalogs instead.   e.g. Add a catalog called dataset2 and then add a
table called table2 inside that.

**Comment by cthrysoe** [comment]
Tried with adding sub-catalogs and it works as expected. Thank you for your help

**Comment by mithunsinghtocode** [comment]
Can you please post the solution on how sub catalog is added for above issue. I am facing similar issue.
