### ISSUE TITLE
Java Wrapper getting error: Statement not supported: CreateTableStatement

### ISSUE THREAD

**Issue by cthrysoe** [google/zetasql#50]
Hi, I am using the ZetaSQL Java wrapper to extract the tables used in a SQL query. When the query contains a "Create table" statement, I am getting a `Statement not supported: CreateTableStatement`.

Is there any way for me to enable "create table" statements when analyzing the query? 

Code sample to reproduce:

```
String sql = "create or replace table project2.dataset2.table2 as SELECT column1 from project1.dataset1.table1";
SimpleCatalog catalog = new SimpleCatalog("tableCatalog");
SimpleCatalog catalProject = catalog.addNewSimpleCatalog("project1");
SimpleCatalog catalDataset = catalProject.addNewSimpleCatalog("dataset1");
SimpleColumn column1 = new SimpleColumn("project1.dataset1.table1", "column1", TypeFactory.createSimpleType(ZetaSQLType.TypeKind.TYPE_STRING));
SimpleTable simpleTable1 = new SimpleTable("table1", Arrays.asList(column1));
catalDataset.addSimpleTable(simpleTable1);
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions());
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
AnalyzerOptions options = new AnalyzerOptions();
options.setPruneUnusedColumns(true);
options.setLanguageOptions(languageOptions);
Analyzer analyzer = new Analyzer(options, catalog);
analyzer.analyzeStatement(sql);
```

Running the above throws:  `INVALID_ARGUMENT: Statement not supported: CreateTableStatement [at 1:1]`

Thank you

**Comment by matthewcbrown** [comment]
I have personally been bit by this one as well.
You also need:
languageOptions.setSupportsAllStatementKinds();

I'm not sure we've thoroughly tested DDL in java, but that should at least get you past analyze.

**Comment by cthrysoe** [comment]
Perfect, thanks @matthewcbrown , just what I was looking for.
