### ISSUE TITLE
No matching signature for function CONCAT for argument types: DATE, DATE. How to add signature?

### ISSUE THREAD

**Issue by cthrysoe** [google/zetasql#52]
Hi there,
I have a BigQuery query that I am trying to parse using the ZetaSql Java wrapper. The query contains a `CONCAT` function call with two date types as argument, however, when I try to parse it I get the error:
```
INVALID_ARGUMENT: No matching signature for function CONCAT for argument types: DATE, DATE. Supported signatures: CONCAT(STRING, [STRING, ...]); CONCAT(BYTES, [BYTES, ...]) [at 1:8]
```
example of the query:
```
select concat(current_date(), current_date())
```
How can I add this signature to the function?
Thank you

**Comment by jshute111** [comment]
This should work if you turn on the LanguageFeature
FEATURE_V_1_3_CONCAT_MIXED_TYPES.

I'm not sure why we have that off by default.  I will check, and see if we
can change the default.

(Otherwise, you can replace builtin function definitions in the Catalog
with your own versions, with different signatures.)

**Comment by christoffer-thrysoe** [comment]
Hi @jshute111 thanks for the reply.

I have tried adding the feature as follows:
```
String sql = "select concat(current_date(), current_date())";
SimpleCatalog catalog = new SimpleCatalog("tableCatalog");
catalog.addZetaSQLFunctions(new ZetaSQLBuiltinFunctionOptions());
LanguageOptions languageOptions = new LanguageOptions();
languageOptions.enableMaximumLanguageFeatures();
languageOptions.enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_V_1_3_CONCAT_MIXED_TYPES);
AnalyzerOptions options = new AnalyzerOptions();
options.setLanguageOptions(languageOptions);
Analyzer analyzer = new Analyzer(options, catalog);
analyzer.analyzeStatement(sql);
```
However, I still get the error:
```
com.google.zetasql.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No matching signature for function CONCAT for argument types: STRING, DATE. Supported signatures: CONCAT(STRING, [STRING, ...]); CONCAT(BYTES, [BYTES, ...]) [at 1:8]
```
Any idea as to why I am still getting the error? Thanks

**Comment by jshute111** [comment]
Try passing your languageOptions into the ZetaSQLBuiltinFunctionOptions()
constructor too.  Here, this option affects Catalog setup rather than
Analyzer behavior.

**Comment by cthrysoe** [comment]
That worked. Thanks for taking the time!
