### ISSUE TITLE
Too many levels of nesting

### ISSUE THREAD

**Issue by borjavb** [google/zetasql#55]
Hello!

I'm trying to run the static Java method `Analyzer.analyzeStatement` over a quite long select statement with multiple CTEs, and I'm getting the following error:

`Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
`
The catalog is properly built and everything works perfectly with smaller queries.

Is it possible to increase this recursion limit or a workaround to parse long SQL statements?

Thank you and Merry Christmas!

**Comment by TvanLeuverden-Devoteam** [comment]
Did you find a workaround?
As I also have this issue.

**Comment by borjavb** [comment]
Unfortunately there's no easy way for this, as the error is from the proto-lite library - so there are two options a) update the ZetaSQL core to increase the recursion level. b) recompile ZetaSQL with a custom version of proto-lite.
