### ISSUE TITLE
How to extract connection in AS statements

### ISSUE THREAD

**Issue by borjavb** [google/zetasql#56]
Hi,

I'm trying to parse the following query through the java implementation:
```
WITH test_table AS (
  SELECT
  column_source as column_alias
  FROM `table_in_catalog`
)

SELECT column_alias FROM test_table
```

But I'm unable to find a visitor that connects **column_source** with **column_alias**. 
I know that you can get the name-alias relationship with `resolvedoutputcolumn`, but that only works for the output columns of the whole query, not with the ones within CTE table...

Is there any way to extract this connection?

Thank you very much!

**Comment by borjavb** [comment]
The only way of extracting this info is to traverse the tree looking for the id reference.

**Comment by masterlittle** [comment]
Hey @borjavb, can you explain a bit on how you managed to do this? I'm trying the same thing and am stuck here!
