### ISSUE TITLE
How to change statement

### ISSUE THREAD

**Issue by serebro** [google/zetasql#58]
Hi

After parsing some query
```
String sql = "SELECT column1 FROM dataset1.table1 AS t1";
ResolvedQueryStmt statement = (ResolvedQueryStmt) Analyzer.analyzeStatement(sql, options, catalog);
```
I need to change the `statement` for example by
1) adding new column `t1.column2 AS c2`
2) adding new condition for where clause `c2 = 1`

Then by this code
```
String sql = Analyzer.buildStatement(statement, catalog);
```
I would like to receive changed query
```
SELECT column1, t1.column2 AS c2 FROM dataset1.table1 AS t1 WHERE c2 = 1
```

Is it possible?
Where can I found an examples in Java?
Thanks.

**Comment by matthewcbrown** [comment]
read-modify-write isn't well supported. There is a Builder interface on ResolvedNode objects:
`Analyzer.buildStatement(statement, catalog).toBuilder().`

The ResolveNode AST code is all generated. If you are able to build in bazel, you can do:
```
bazel build java/...
# Generated Resolved AST classes
ls bazel-bin/java/com/google/zetasql/resolvedast/ResolvedNodes.java 

```

You can see some example usage in
[ResolvedNodesTest.java](https://github.com/google/zetasql/blob/master/javatests/com/google/zetasql/resolvedast/ResolvedNodesTest.java)
However, it doesn't really handle this case.

So, if we look at the AST for this query (I fiddled with it a little):

```
# Create a fake input.csv to act as 'table1'
bazel build //zetasql/tools/execute_query/...
printf 'column1\n5' > input.csv
bazel-bin/zetasql/tools/execute_query/execute_query --mode=resolve --table_spec="table1=csv:$(pwd)/input.csv" SELECT column1 FROM table1 AS t1

QueryStmt
+-output_column_list=
| +-table1.column1#1 AS column1 [STRING]
+-query=
  +-ProjectScan
    +-column_list=[table1.column1#1]
    +-input_scan=
      +-TableScan(column_list=[table1.column1#1], table=table1, column_index_list=[0], alias="t1")

```

So, to handle this case you would have to basically do a 'toBuilder' on the top node, clone all of it's children, and rebuild the AST.  Or maybe start with a fresh builder (`QueryStmt.newBuilder()`) and build a modified query in that. So, it is theoretically possible, but not easy.  On the C++ side there is the 'ResolvedASTDeepCopyVisitor' (also generated) which makes this a little more straightforward. Some examples can be found in:
[resolved_ast_deep_copy_visitor_test.cc](https://github.com/google/zetasql/blob/master/zetasql/resolved_ast/resolved_ast_deep_copy_visitor_test.cc)

Can you talk a little more about your use case?

**Comment by serebro** [comment]
@matthewcbrown thank you very much for builder examples.

In my case I have some business rules (according to user permissions) that should be applied to incoming SQL query.
Example: business rule - `do not show name and show balance more then $1000`
`SELECT * FROM accounts` -> `parsing` -> `modifying` -> `SELECT NULL AS name FROM accounts WHERE balance > 1000` outgoing query will be passed to JDBC.

I tried to use visitor pattern like this

```java
    statement.accept(new ResolvedNodes.Visitor() {
        @Override
        public void visit(ResolvedNodes.ResolvedProjectScan node) {
            ImmutableList.Builder<ResolvedColumn> columnListBuilder = ImmutableList.builder();
            columnListBuilder.add(column);
            ImmutableList<ResolvedColumn> columnList = columnListBuilder.build();
            node = node.toBuilder().setColumnList(columnList).build();
            super.visit(node);
        }
    });
```

but it does not work, the statement was not changed

**Comment by matthewcbrown** [comment]
ResolveNode objects are immutable, so when you call 'toBuilder' it's create a new object.
So, you have to recursively rebuild a complete new node tree using new all new nodes (which is what the deepcopyvisitor does on the C++ side).

**Comment by serebro** [comment]
Does this mean that I cannot do this using Java? If not, please point me to some examples of code.

**Comment by serebro** [comment]
Thank you.

**Comment by matthewcbrown** [comment]
Most recent release has a rewriting visitor which hopefully makes this much easier, see RewritingVisitorTest.java for some examples.
