### ISSUE TITLE
extractTableNamesFromStatement fails when analyzeStatement works

### ISSUE THREAD

**Issue by serebro** [google/zetasql#64]
Hi

Trying to extract table names I receive an exception.
```java
String sql = "SELECT * FROM projectid-123.ds.tbl";
Analyzer.extractTableNamesFromStatement(sql);
```
```
Syntax error: Table name contains '-' character. It needs to be quoted: `projectid-123.ds.tbl` [at 1:15]
```

but analyzing the query by `Analyzer.analyzeStatement` it works.

Is it possible to fix `extractTableNamesFromStatement` behaviour to have a consistency.

PS: version 2021-02-1

Thank you.

**Comment by serebro** [comment]
Not relevant anymore

**Comment by sridhar562345** [comment]
Hi @serebro 

Can you provide me with the rough steps of extracting table and column names from SQL queries?
