### ISSUE TITLE
liblocal_service_jni.dylib is missing for zetasql-jni-channel-darwin on maven version `2021.03.1`

### ISSUE THREAD

**Issue by MartinSahlen** [google/zetasql#67]
Essentially, this means that version 2021.03.1 will not run at all on MacOS (it crashes, not finding a channel provider). 

I'm aware that there are no guarantees for compatibility, but just wanted to let the maintainers know that the contents of [this](https://mvnrepository.com/artifact/com.google.zetasql/zetasql-jni-channel-darwin/2021.03.1) is completely empty. This was also verified by downloading and extracting 2021.02.1 and verifying the existence of the dylib file here, but not in the most recent version.

**Comment by matthewcbrown** [comment]
We were messing around with our build process a bit, seems like it went sideways. 2021.03.02 was pushed yesterday (same repo, new binaries). Does that one look alright?

**Comment by MartinSahlen** [comment]
I can confirm that the new version's size went from  [304 bytes to 19M](https://mvnrepository.com/artifact/com.google.zetasql/zetasql-jni-channel-darwin/2021.03.2) and when further downloading and extracting the zip the `dylib` file is indeed present. When running existing ZetaSQL code this also now works in MacOS. Thanks a bunch!!

**Comment by MartinSahlen** [comment]
Closing as this is considered resolved from my side.
