### ISSUE TITLE
Thanks for maintaining this!

### ISSUE THREAD

**Issue by borjavb** [google/zetasql#79]
I just want to thank you all for open sourcing ZetaSQL and constantly keeping it up to date. I haven't even discovered its full potential but it's helped a lot to build really nice column level lineage tools.

I've written a small blog post about how we are using it right now to parse all our dbt models in BigQuery https://medium.com/data-monzo/mapping-our-data-journey-with-column-lineage-56209c00606d

Again, thanks team!! ❤️

**Comment by matthewcbrown** [comment]
Thanks for the note!
