### ISSUE TITLE
BigQuery _PARTITIONTIME support

### ISSUE THREAD

**Issue by cthrysoe** [google/zetasql#87]
Hi, In BigQuery, tables can be partitioned by ingestion-time and a partition can be referenced as:

```
select * from dataset.table where _PARTITIONTIME = '2022-01-01'
```
[Docs](https://cloud.google.com/bigquery/docs/querying-partitioned-tables#query_an_ingestion-time_partitioned_table)

This gives the error:
```
com.google.zetasql.SqlException: Unrecognized name: _PARTITIONTIME
````
Can I add support for this somehow?
Thanks

**Comment by JordyHeusdensDT** [comment]
You need to add this to your SimpleTable as a PseudoColumn as far as I know. It would look something like underneath:

```
simpleTable.addSimpleColumn(
                        "_PARTITIONTIME",
                        TypeFactory.createSimpleType(ZetaSQLType.TypeKind.TYPE_TIMESTAMP),
                        true,
                        false);
```

Your SimpleTable is in the end part of your SimpleCatalog.

**Comment by cthrysoe** [comment]
Thanks @JordyHeusdensDT, that did the trick!
