### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by kileys** [google/zetasql#89]
Java 17 removed the `sun/nio/ch/SocketChannelImpl` constructor used here[1] and now throws `java.lang.NoSuchMethodError: <init>`. Can support be added to use an available constructor?

[1] https://github.com/google/zetasql/blob/master/zetasql/local_service/local_service_jni.cc#L117-L120

**Comment by matthewcbrown** [comment]
This should be fixed in 2022.04.1, please give it a try (thanks @apilloud!)

**Comment by apilloud** [comment]
Confirmed this works in https://github.com/apache/beam/pull/17434
