### ISSUE TITLE
SimpleColumn.java lacks public constructors

### ISSUE THREAD

**Issue by christophstockhusen** [google/zetasql#9]
The constructors of `SimpleColumn.java` are package-protected although the class itself is public. Hence, the constructors should also be public.

**Comment by MartinSahlen** [comment]
Oh nice, alas I was wrong about `no constructors and also no Factory or Builder classes to create them`. But happy to be wrong! The lack of documentation seems to be the biggest issue then.

**Comment by matthewcbrown** [comment]
Fixed in c610a21ffdc110293c1c7bd255a2674ebc7ec7a8 (the constructors, not the documentation).
