### ISSUE TITLE
Additional analytic/scripting support?

### ISSUE THREAD

**Issue by justinwhite** [google/zetasql#94]
Is there any appetite/timeline for supporting either [QUALIFY](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause) or [Loops](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting#loop)? 

With 2022.02.01 I'm seeing:

> `INVALID_ARGUMENT: Syntax error: Expected ")" but got identifier "QUALIFY" [at 55:7]`

> `INVALID_ARGUMENT: Syntax error: Expected keyword END but got identifier "loopi" [at 54:9]`

Suggesting neither is supported from the c++ api method `ExtractTableNamesFromScript`.

**Comment by sridhar562345** [comment]
@justinwhite can you give me the rough steps to extract tables and columns using zetasql?

I was able to build zetasql and execute query as shown in the documentation.
