### ISSUE TITLE
DebugPrintableNode isn't included in 2022.02.1

### ISSUE THREAD

**Issue by justinwhite** [google/zetasql#99]
Looks like `DebugPrintableNode` is required to use ResolvedNode in `zetasql-client` release 2022.02.1: https://github.com/google/zetasql/blob/2022.02.1/java/com/google/zetasql/resolvedast/ResolvedNode.java#L42

but the java_library build rule/class doesn't seem to be included in the generated files for the release:

> cannot access com.google.zetasql.DebugPrintableNode

Per https://github.com/google/zetasql/search?q=debug_printable_node, seems like if it wasn't included under `com.google.zetasql`, it'd be under `com.google.zetasql.parser` or `com.google.zetasql.resolvedast`, but no [generated] class found in those directories either.

**Comment by justinwhite** [comment]
Copied the interface in from https://github.com/google/zetasql/blob/2022.02.1/java/com/google/zetasql/DebugPrintableNode.java and calls to `ResolvedNode` work fine, so I'm guessing this is just a build/release issue (or choice).

**Comment by tha23rd** [comment]
> Patched the interface in from https://github.com/google/zetasql/blob/2022.02.1/java/com/google/zetasql/DebugPrintableNode.java and calls to `ResolvedNode` work fine, so I'm guessing this is just a build/release issue (or choice).

Hey Justin, running into this same issue!

Would you mind explaining how you were able to patch the interface?

**Comment by matthewcbrown** [comment]
I think I've got this fixed in 2022.04.1

**Comment by tha23rd** [comment]
> 

Can confirm, is fixed!

One quick question while I got you here: Is QUALIFY not supported in the java version?

I have the following:

```java
        AnalyzerOptions analyzerOptions = new AnalyzerOptions();
        analyzerOptions.setPruneUnusedColumns(true);
        analyzerOptions.setAllowUndeclaredParameters(true);
        LanguageOptions languageOptions = new LanguageOptions();
        languageOptions.setSupportsAllStatementKinds();
        languageOptions.enableMaximumLanguageFeatures();
        languageOptions.enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_V_1_3_ALLOW_DASHES_IN_TABLE_NAME);
        languageOptions.enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_V_1_3_QUALIFY);
        languageOptions.enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_V_1_3_SCRIPT_LABEL);
        languageOptions.enableLanguageFeature(ZetaSQLOptions.LanguageFeature.FEATURE_ANALYTIC_FUNCTIONS);
        analyzerOptions.setLanguageOptions(languageOptions);
 ```
 
 But am still seeing: `com.google.zetasql.SqlException: QUALIFY is not supported [at 4:11]`

**Comment by matthewcbrown** [comment]
can you file a separate issue with more details (what api are you calling, what is the query, etc.)

**Comment by tha23rd** [comment]
> can you file a separate issue with more details (what api are you calling, what is the query, etc.)

Created an issue here: https://github.com/google/zetasql/issues/103

Thanks!!
